// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Ejercicio3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ejercicio3() {
    driver.get("https://www.selenium.dev/");
    driver.manage().window().setSize(new Dimension(1214, 728));
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span")).click();
    assertThat(driver.findElement(By.cssSelector(".d-1")).getText(), is("Downloads"));
    assertThat(driver.findElement(By.cssSelector(".mt-3")).getText(), is("Below is where you can find the latest releases of all the Selenium components."));
    assertThat(driver.findElement(By.cssSelector(".lead:nth-child(3)")).getText(), is("You can also find a list of previous releases, source code, and additional information for Maven users."));
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) span")).click();
    assertThat(driver.findElement(By.cssSelector(".d-1")).getText(), is("Projects"));
    assertThat(driver.findElement(By.cssSelector(".lead")).getText(), is("Selenium has many projects that combine to form a versatile testing system."));
    assertThat(driver.findElement(By.cssSelector(".alert-webdriver > .alert-heading")).getText(), is("Selenium WebDriver"));
  }
}
