// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Ejercicio2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ejercicio2() {
    driver.get("https://automationexercise.com/");
    driver.manage().window().setSize(new Dimension(1112, 665));
    js.executeScript("window.scrollTo(0,89.5999984741211)");
    driver.findElement(By.linkText(" Products")).click();
    js.executeScript("window.scrollTo(0,152.8000030517578)");
    driver.findElement(By.id("search_product")).click();
    driver.findElement(By.id("search_product")).sendKeys("Green Side Placket Detail T-Shirt");
    driver.findElement(By.cssSelector(".fa-search")).click();
    js.executeScript("window.scrollTo(0,4.800000190734863)");
    js.executeScript("window.scrollTo(0,528)");
    driver.findElement(By.linkText("View Product")).click();
  }
}
